services:
  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: browser-chromium
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
      - TITLE=Docker Chromium
      - SELKIES_FRAMERATE=50
      - LIBVA_DRIVER_NAME=iHD
      - SELKIES_MANUAL_WIDTH=1920
      - SELKIES_MANUAL_HEIGHT=1080
      - SELKIES_IS_MANUAL_RESOLUTION_MODE=true
      - SELKIES_VIDEO_BITRATE=20
      - SELKIES_H264_CRF=21
      - CHROME_CLI=--ignore-gpu-blocklist --enable-gpu-rasterization --enable-zero-copy --num-raster-threads=4 --enable-features=VaapiVideoDecoder,VaapiVideoEncoder,CanvasOopRasterization --disable-features=UseChromeOSDirectVideoDecoder --autoplay-policy=no-user-gesture-required
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./config:/config
      - ./config/custom-cont-init.d:/custom-cont-init.d:ro
    ports:
      - 8085:3000
      - 8086:3001
    shm_size: 1gb
    restart: unless-stopped

